# Generated by Django 2.2 on 2019-06-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='movie_images')),
            ],
        ),
        migrations.CreateModel(
            name='JsonMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='json_images')),
                ('period', models.CharField(max_length=100)),
            ],
        ),
    ]
